import { useState, useRef, useEffect } from 'react';
import theme from '../theme';
import { useTheme } from '../context/ThemeContext';
import {
  ChevronLeft, Shield, AlertTriangle, Save, Check, Plus, X,
  Target, Search, Sparkles, Send, Globe, Loader, Edit, ChevronDown,
  Info, Eye,
} from 'lucide-react';
import { NEXTIQ_GOALS, NEXTIQ_GUARDRAILS } from '../data/nextiqConfig';

const AI_TEMPLATES = [
  {
    keywords: ['credit', 'refund', 'money', 'dollar', '$', 'amount', 'limit', 'financial', 'payment'],
    generate: () => ({
      name: 'NextIQ Financial Action Limit',
      description: 'Prevents NextIQ from auto-executing financial actions (credits, refunds, plan changes) above a defined threshold. Requires agent confirmation before the AI pipeline processes the transaction.',
      severity: 'critical',
      level: 'goal',
      condition: 'When NextIQ attempts to auto-execute Apply_Billing_Credit, Process_Refund, or Modify_Plan AND the transaction amount exceeds the configured threshold',
      constraint: 'Block NextIQ auto-execution. Hold the action in pending state. Surface a manual NBA to the agent with full transaction details and a "Requires Approval" badge. Log blocked attempts for audit.',
      applicableGoals: ['goal-chargeback', 'goal-billing-plan'],
    }),
  },
  {
    keywords: ['pii', 'personal', 'data', 'privacy', 'mask', 'ssn', 'social security', 'card number', 'email address'],
    generate: () => ({
      name: 'NextIQ PII Output Masking',
      description: 'Scans all AI-generated text (NBA suggestions, replies, summaries) for personally identifiable information and masks it before delivery. Does not affect raw tool-response data shown to the agent.',
      severity: 'warning',
      level: 'organization',
      condition: 'On every text generated by the NextIQ pipeline — REPLY drafts, NBA descriptions, conversation summaries, and KB excerpts — before output to the agent or customer',
      constraint: 'Regex scan for PII patterns (email, SSN, card numbers, phone). Mask to partial format: j***@domain.com, ****4891. Tool-response data is exempt — masking applies only to NextIQ-generated text.',
      applicableGoals: [],
    }),
  },
  {
    keywords: ['escalat', 'supervisor', 'manager', 'tier 2', 'tier2', 'senior', 'handoff', 'transfer', 'timeout', 'unresolved'],
    generate: () => ({
      name: 'NextIQ Auto-Escalation Timeout',
      description: 'Forces NextIQ to surface an escalation NBA or auto-escalate the conversation when the AI cannot resolve the issue within a configurable time window.',
      severity: 'warning',
      level: 'goal',
      condition: 'When the active goal sub-agent has been running for more than the configured timeout AND no resolution action has been completed by NextIQ',
      constraint: 'NextIQ surfaces a priority escalation NBA to the agent. In Autopilot, trigger auto-escalation to the supervisor queue with full conversation context attached. Log the timeout event.',
      applicableGoals: ['goal-account-security'],
    }),
  },
  {
    keywords: ['tone', 'language', 'professional', 'empathy', 'rude', 'offensive', 'sarcas', 'polite', 'rewrite'],
    generate: () => ({
      name: 'NextIQ Tone Analysis Gate',
      description: 'Runs tone analysis on all AI-generated text before delivery. Blocks or rewrites responses that score below the professional threshold — prevents sarcastic, dismissive, or blame-placing language from reaching the customer.',
      severity: 'warning',
      level: 'organization',
      condition: 'On every REPLY draft, NBA text, and suggested response generated by the NextIQ pipeline — before output',
      constraint: 'Run tone analysis on generated text. If below threshold: in Autopilot, auto-rewrite the response. In assist mode, surface a "Tone Warning" badge on the draft with a suggested revision.',
      applicableGoals: [],
    }),
  },
  {
    keywords: ['legal', 'lawyer', 'attorney', 'compliance', 'court', 'lawsuit', 'litigation', 'regulat'],
    generate: () => ({
      name: 'NextIQ Legal Safe Mode',
      description: 'When legal keywords are detected in the conversation, restricts the NextIQ pipeline to reply-only mode — all ACTION NBAs are disabled and the supervisor is immediately notified.',
      severity: 'critical',
      level: 'organization',
      condition: 'Customer message contains legal keywords: "lawyer", "attorney", "legal action", "sue", "litigation", "court", "regulatory complaint", "FTC", "BBB"',
      constraint: 'Switch NextIQ to REPLY-only mode — disable all ACTION NBAs in the pipeline. Trigger Escalate_To_Supervisor automatically. Log all messages for legal review. Safe mode persists until supervisor clears it.',
      applicableGoals: [],
    }),
  },
  {
    keywords: ['autopilot', 'auto', 'automatic', 'autonomous', 'unmanned', 'block', 'prevent', 'restrict'],
    generate: () => ({
      name: 'NextIQ Autopilot Safety Boundary',
      description: 'Prevents NextIQ from auto-executing high-risk actions in Autopilot mode, even if the action is in the allowed automation list. Requires explicit agent confirmation.',
      severity: 'critical',
      level: 'goal',
      condition: 'NextIQ Autopilot mode is active AND the action category is flagged as high-risk (financial, account modification, data deletion, plan changes)',
      constraint: 'Block auto-execution in the NextIQ pipeline. Surface as a manual NBA with a prominent "Requires Agent Approval" badge. Log all blocked auto-execution attempts.',
      applicableGoals: ['goal-chargeback', 'goal-billing-plan'],
    }),
  },
  {
    keywords: ['downgrad', 'vip', 'recommend', 'suggest', 'plan change', 'churn'],
    generate: () => ({
      name: 'NextIQ VIP Downgrade Prevention',
      description: 'Prevents the NextIQ pipeline from recommending plan downgrades or cost-reduction NBAs to VIP-tier customers, protecting revenue retention.',
      severity: 'warning',
      level: 'goal',
      condition: 'When NextIQ generates a plan-change NBA AND the recommended action is a downgrade AND the customer account is tagged as VIP or Enterprise tier',
      constraint: 'Suppress the downgrade NBA from the agent view. Log the suppression. Optionally surface an upsell or retention-focused NBA instead.',
      applicableGoals: ['goal-billing-plan'],
    }),
  },
];

function generateFromInput(input) {
  const lower = input.toLowerCase();
  for (const tpl of AI_TEMPLATES) {
    if (tpl.keywords.some(kw => lower.includes(kw))) {
      return tpl.generate(input);
    }
  }
  return {
    name: 'Custom NextIQ Constraint',
    description: input.slice(0, 200),
    severity: 'warning',
    level: 'organization',
    condition: `When the NextIQ pipeline detects: "${input.slice(0, 100)}" — evaluated on every AI-generated output and action attempt`,
    constraint: 'Block or flag the AI output/action. Surface a warning to the agent. Log the trigger for audit. In Autopilot, pause auto-execution and request human review.',
    applicableGoals: [],
  };
}

const EXAMPLE_PROMPTS = [
  'Block NextIQ from auto-executing any refund above $500 in Autopilot mode',
  'Never include full credit card numbers or SSN in AI-generated NBA text',
  'If legal keywords are detected, restrict NextIQ to reply-only mode — disable all action NBAs',
  'Require agent approval before NextIQ can trigger account security modifications',
  'Prevent NextIQ from recommending plan downgrades to VIP customers',
];

export default function NextIQGuardrailCreate({ onBack, onSave, allGoals: allGoalsProp, customGoals = [], editGuardrail }) {
  const { theme: themeMode } = useTheme();
  const colors = theme.themes[themeMode];
  const isEdit = !!editGuardrail;

  const [step, setStep] = useState(isEdit ? 'review' : 'describe');
  const [userInput, setUserInput] = useState('');
  const [showBanner, setShowBanner] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationProgress, setGenerationProgress] = useState(0);
  const [generationStage, setGenerationStage] = useState('');

  const [name, setName] = useState(editGuardrail?.name || '');
  const [description, setDescription] = useState(editGuardrail?.description || '');
  const [severity, setSeverity] = useState(editGuardrail?.severity || 'critical');
  const [status, setStatus] = useState(editGuardrail?.status || 'active');
  const [level, setLevel] = useState(editGuardrail?.level || 'organization');
  const [condition, setCondition] = useState(editGuardrail?.condition || '');
  const [constraint, setConstraint] = useState(editGuardrail?.constraint || '');
  const [selectedGoals, setSelectedGoals] = useState(editGuardrail?.applicableGoals || []);
  const [showGoalPicker, setShowGoalPicker] = useState(false);
  const [goalSearch, setGoalSearch] = useState('');
  const [saved, setSaved] = useState(false);

  const pickerRef = useRef(null);
  const textareaRef = useRef(null);

  useEffect(() => {
    const handler = (e) => {
      if (pickerRef.current && !pickerRef.current.contains(e.target)) {
        setShowGoalPicker(false);
        setGoalSearch('');
      }
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, []);

  useEffect(() => {
    if (step === 'describe' && textareaRef.current) {
      textareaRef.current.focus();
    }
  }, [step]);

  const allGoals = allGoalsProp || [...NEXTIQ_GOALS, ...customGoals];
  const availableGoals = allGoals.filter(g => !selectedGoals.includes(g.id));
  const filteredGoals = availableGoals.filter(g =>
    !goalSearch || g.name.toLowerCase().includes(goalSearch.toLowerCase())
  );

  const nextId = `GR-${String(NEXTIQ_GUARDRAILS.length + 1).padStart(3, '0')}`;

  const isValid = name.trim() && description.trim() && condition.trim() && constraint.trim();

  const handleGenerate = () => {
    if (!userInput.trim()) return;
    setIsGenerating(true);
    setGenerationProgress(0);
    setGenerationStage('Analyzing your requirements...');

    const stages = [
      { at: 15, text: 'Identifying guardrail category...' },
      { at: 35, text: 'Mapping trigger conditions...' },
      { at: 55, text: 'Defining enforcement constraints...' },
      { at: 75, text: 'Selecting severity and scope...' },
      { at: 90, text: 'Finalizing guardrail configuration...' },
    ];

    let progress = 0;
    const interval = setInterval(() => {
      progress += Math.random() * 8 + 2;
      if (progress >= 100) progress = 100;
      setGenerationProgress(Math.round(progress));

      const currentStage = [...stages].reverse().find(s => progress >= s.at);
      if (currentStage) setGenerationStage(currentStage.text);

      if (progress >= 100) {
        clearInterval(interval);
        setTimeout(() => {
          const result = generateFromInput(userInput);
          setName(result.name);
          setDescription(result.description);
          setSeverity(result.severity);
          setLevel(result.level);
          setCondition(result.condition);
          setConstraint(result.constraint);
          setSelectedGoals(result.applicableGoals);
          setIsGenerating(false);
          setStep('review');
        }, 400);
      }
    }, 120);
  };

  const handleSave = () => {
    if (!isValid) return;
    const guardrailData = {
      id: isEdit ? editGuardrail.id : nextId,
      name: name.trim(),
      description: description.trim(),
      severity,
      status,
      level,
      condition: condition.trim(),
      constraint: constraint.trim(),
      applicableGoals: level === 'organization' ? [] : selectedGoals,
    };
    setSaved(true);
    setTimeout(() => onSave(guardrailData), 600);
  };

  const inputStyle = {
    width: '100%', padding: '10px 14px', borderRadius: theme.radii.md,
    border: `1px solid ${colors.border}`, backgroundColor: colors.inputBackground,
    color: colors.text, fontSize: '13px', fontFamily: theme.fonts.body,
    outline: 'none', boxSizing: 'border-box',
  };

  const sectionStyle = {
    padding: '24px', borderRadius: theme.radii.xl,
    backgroundColor: colors.surface, border: `1px solid ${colors.border}`,
    marginBottom: '20px',
  };

  const sevColor = severity === 'critical' ? theme.colors.error : theme.colors.warning;
  const sevBg = severity === 'critical' ? theme.colors.errorMuted : theme.colors.warningMuted;

  if (saved) {
    return (
      <div style={{ maxWidth: '900px', margin: '0 auto', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: '400px' }}>
        <div style={{
          width: '64px', height: '64px', borderRadius: '50%',
          backgroundColor: theme.colors.successMuted, display: 'flex', alignItems: 'center', justifyContent: 'center',
          marginBottom: '16px',
        }}>
          <Check size={32} color={theme.colors.success} />
        </div>
        <h2 style={{ fontSize: '20px', fontWeight: 700, color: colors.text, margin: '0 0 8px' }}>
          {isEdit ? 'Guardrail Updated' : 'Guardrail Created'}
        </h2>
        <p style={{ fontSize: '14px', color: colors.textSecondary, margin: 0 }}>
          <strong>{name}</strong> has been {isEdit ? 'updated successfully' : 'added to the Guardrails registry'}.
        </p>
      </div>
    );
  }

  // ── STEP 1: Natural Language Description ──
  if (step === 'describe') {
    return (
      <div style={{ maxWidth: '900px', margin: '0 auto' }}>
        <button onClick={onBack} style={{
          display: 'flex', alignItems: 'center', gap: '6px', padding: '6px 0', border: 'none',
          backgroundColor: 'transparent', color: theme.colors.blue, fontSize: '13px', fontWeight: 600,
          fontFamily: theme.fonts.body, cursor: 'pointer', marginBottom: '16px',
        }}>
          <ChevronLeft size={16} /> Back to Guardrails
        </button>

        <div style={{ textAlign: 'center', marginBottom: '40px' }}>
          <div style={{
            width: '56px', height: '56px', borderRadius: '50%', margin: '0 auto 16px',
            background: `linear-gradient(135deg, ${theme.colors.blue}, ${theme.colors.purple})`,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>
            <Sparkles size={28} color="#fff" />
          </div>
          <h1 style={{ fontSize: '24px', fontWeight: 700, color: colors.text, margin: '0 0 8px' }}>
            Create a Guardrail with AI
          </h1>
          <p style={{ fontSize: '15px', color: colors.textSecondary, margin: 0, maxWidth: '560px', marginLeft: 'auto', marginRight: 'auto', lineHeight: 1.6 }}>
            Describe how you want to constrain NextIQ's behavior. Guardrails control the <strong style={{ color: colors.text }}>AI system</strong> — not the agent.
          </p>
        </div>

        {showBanner && (
          <div style={{
            padding: '12px 16px', borderRadius: theme.radii.lg, marginBottom: '20px',
            backgroundColor: `${theme.colors.blue}05`, border: `1px solid ${theme.colors.blue}20`,
            display: 'flex', alignItems: 'flex-start', gap: '10px',
          }}>
            <Info size={16} color={theme.colors.blue} style={{ flexShrink: 0, marginTop: '1px' }} />
            <div style={{ flex: 1, fontSize: '12px', color: colors.textSecondary, lineHeight: 1.5 }}>
              <strong style={{ color: colors.text }}>Guardrails vs Coaching Rules:</strong> Guardrails constrain what the <strong>AI system</strong> can do — block actions, mask AI-generated text, restrict NextIQ's outputs. To coach the <strong>human agent's</strong> behavior (greetings, empathy, verification steps), use <strong>Coaching Rules</strong> instead.
            </div>
            <button onClick={() => setShowBanner(false)} style={{
              padding: '2px', border: 'none', backgroundColor: 'transparent', cursor: 'pointer', display: 'flex', flexShrink: 0,
            }}>
              <X size={14} color={colors.textTertiary} />
            </button>
          </div>
        )}

        {/* Input area */}
        <div style={{
          ...sectionStyle,
          border: `2px solid ${theme.colors.blue}30`,
          background: `linear-gradient(180deg, ${colors.surface} 0%, ${theme.colors.blue}03 100%)`,
          marginBottom: '16px',
        }}>
          <div style={{ position: 'relative' }}>
            <textarea
              ref={textareaRef}
              value={userInput}
              onChange={e => setUserInput(e.target.value)}
              onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey && userInput.trim()) { e.preventDefault(); handleGenerate(); } }}
              placeholder="Describe what you want this guardrail to enforce..."
              rows={4}
              style={{
                ...inputStyle,
                fontSize: '15px',
                lineHeight: 1.7,
                resize: 'vertical',
                minHeight: '120px',
                paddingRight: '60px',
                border: `1px solid ${theme.colors.blue}25`,
                backgroundColor: colors.surface,
              }}
            />
            <button
              onClick={handleGenerate}
              disabled={!userInput.trim()}
              style={{
                position: 'absolute', bottom: '12px', right: '12px',
                width: '40px', height: '40px', borderRadius: '50%',
                border: 'none', cursor: userInput.trim() ? 'pointer' : 'not-allowed',
                background: userInput.trim()
                  ? `linear-gradient(135deg, ${theme.colors.blue}, ${theme.colors.purple})`
                  : colors.surfaceHover,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                transition: theme.transitions.fast,
                opacity: userInput.trim() ? 1 : 0.5,
              }}
            >
              <Send size={18} color={userInput.trim() ? '#fff' : colors.textTertiary} />
            </button>
          </div>
        </div>

        {/* Example prompts */}
        <div style={{ marginBottom: '20px' }}>
          <div style={{ fontSize: '12px', fontWeight: 600, color: colors.textSecondary, marginBottom: '10px' }}>
            Try an example:
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {EXAMPLE_PROMPTS.map((prompt, i) => (
              <button
                key={i}
                onClick={() => setUserInput(prompt)}
                style={{
                  padding: '10px 16px', borderRadius: theme.radii.md,
                  border: `1px solid ${colors.border}`, backgroundColor: colors.surface,
                  color: colors.text, fontSize: '13px', fontFamily: theme.fonts.body,
                  cursor: 'pointer', textAlign: 'left', transition: theme.transitions.fast,
                  display: 'flex', alignItems: 'center', gap: '10px',
                }}
                onMouseEnter={e => { e.currentTarget.style.backgroundColor = colors.surfaceHover; e.currentTarget.style.borderColor = theme.colors.blue + '40'; }}
                onMouseLeave={e => { e.currentTarget.style.backgroundColor = colors.surface; e.currentTarget.style.borderColor = colors.border; }}
              >
                <Sparkles size={14} color={theme.colors.blue} style={{ flexShrink: 0 }} />
                {prompt}
              </button>
            ))}
          </div>
        </div>

        {/* Manual creation link */}
        <div style={{ textAlign: 'center', padding: '16px 0' }}>
          <button
            onClick={() => setStep('review')}
            style={{
              padding: 0, border: 'none', backgroundColor: 'transparent',
              color: colors.textSecondary, fontSize: '13px', fontFamily: theme.fonts.body,
              cursor: 'pointer', textDecoration: 'underline',
            }}
          >
            or create manually without AI
          </button>
        </div>
      </div>
    );
  }

  // ── AI Generating Animation ──
  if (isGenerating) {
    return (
      <div style={{ maxWidth: '900px', margin: '0 auto', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: '400px' }}>
        <div style={{
          width: '80px', height: '80px', borderRadius: '50%', marginBottom: '24px',
          background: `linear-gradient(135deg, ${theme.colors.blue}15, ${theme.colors.purple}15)`,
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          position: 'relative',
        }}>
          <Sparkles size={36} color={theme.colors.blue} style={{ animation: 'pulse 1.5s ease-in-out infinite' }} />
          <div style={{
            position: 'absolute', inset: 0, borderRadius: '50%',
            border: `3px solid transparent`,
            borderTopColor: theme.colors.blue,
            animation: 'spin 1s linear infinite',
          }} />
        </div>
        <h2 style={{ fontSize: '20px', fontWeight: 700, color: colors.text, margin: '0 0 8px' }}>
          Generating Guardrail
        </h2>
        <p style={{ fontSize: '14px', color: colors.textSecondary, margin: '0 0 24px', textAlign: 'center' }}>
          {generationStage}
        </p>

        {/* Progress bar */}
        <div style={{
          width: '320px', height: '6px', borderRadius: '3px',
          backgroundColor: colors.surfaceHover, overflow: 'hidden',
        }}>
          <div style={{
            height: '100%', borderRadius: '3px',
            background: `linear-gradient(90deg, ${theme.colors.blue}, ${theme.colors.purple})`,
            width: `${generationProgress}%`,
            transition: 'width 0.3s ease',
          }} />
        </div>
        <span style={{ fontSize: '12px', color: colors.textTertiary, marginTop: '8px' }}>
          {generationProgress}%
        </span>

        {/* User's input shown as context */}
        <div style={{
          marginTop: '32px', padding: '14px 20px', borderRadius: theme.radii.lg,
          backgroundColor: colors.surfaceHover, border: `1px solid ${colors.border}`,
          maxWidth: '480px', width: '100%',
        }}>
          <div style={{ fontSize: '10px', fontWeight: 700, color: colors.textTertiary, textTransform: 'uppercase', letterSpacing: '0.4px', marginBottom: '6px' }}>
            Your Description
          </div>
          <div style={{ fontSize: '13px', color: colors.text, lineHeight: 1.5 }}>
            "{userInput}"
          </div>
        </div>

        <style>{`
          @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
          @keyframes pulse { 0%, 100% { opacity: 1; transform: scale(1); } 50% { opacity: 0.7; transform: scale(0.95); } }
        `}</style>
      </div>
    );
  }

  // ── STEP 2: Review & Edit Generated Guardrail ──
  return (
    <div style={{ maxWidth: '900px', margin: '0 auto' }}>
      <button onClick={onBack} style={{
        display: 'flex', alignItems: 'center', gap: '6px', padding: '6px 0', border: 'none',
        backgroundColor: 'transparent', color: theme.colors.blue, fontSize: '13px', fontWeight: 600,
        fontFamily: theme.fonts.body, cursor: 'pointer', marginBottom: '16px',
      }}>
        <ChevronLeft size={16} /> Back to Guardrails
      </button>

      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '28px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          {userInput && !isEdit ? (
            <div style={{
              width: '32px', height: '32px', borderRadius: '50%',
              background: `linear-gradient(135deg, ${theme.colors.blue}, ${theme.colors.purple})`,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}>
              <Sparkles size={16} color="#fff" />
            </div>
          ) : (
            <Shield size={22} color={theme.colors.warning} />
          )}
          <h1 style={{ fontSize: '22px', fontWeight: 700, color: colors.text, margin: 0 }}>
            {isEdit ? 'Edit Guardrail' : userInput ? 'AI-Generated Guardrail' : 'Create New Guardrail'}
          </h1>
          <span style={{
            padding: '3px 10px', borderRadius: theme.radii.full, fontSize: '10px', fontWeight: 700,
            backgroundColor: sevBg, color: sevColor, textTransform: 'uppercase',
          }}>{severity}</span>
        </div>
        {userInput && !isEdit && (
          <button
            onClick={() => { setStep('describe'); }}
            style={{
              padding: '6px 14px', borderRadius: theme.radii.md,
              border: `1px solid ${theme.colors.blue}30`, backgroundColor: `${theme.colors.blue}06`,
              color: theme.colors.blue, fontSize: '12px', fontWeight: 600,
              cursor: 'pointer', fontFamily: theme.fonts.body,
              display: 'flex', alignItems: 'center', gap: '5px',
            }}
          >
            <Sparkles size={12} /> Regenerate
          </button>
        )}
      </div>

      {userInput && !isEdit && (
        <div style={{
          padding: '12px 16px', borderRadius: theme.radii.lg, marginBottom: '20px',
          background: `linear-gradient(90deg, ${theme.colors.blue}06, ${theme.colors.purple}06)`,
          border: `1px solid ${theme.colors.blue}15`,
          display: 'flex', alignItems: 'center', gap: '10px',
        }}>
          <Sparkles size={14} color={theme.colors.blue} />
          <span style={{ fontSize: '12px', color: colors.textSecondary }}>
            Generated from: <strong style={{ color: colors.text }}>"{userInput}"</strong>
          </span>
        </div>
      )}

      {/* ── 1. Identity ── */}
      <div style={sectionStyle}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '14px' }}>
          <Shield size={15} color={theme.colors.warning} />
          <span style={{ fontSize: '14px', fontWeight: 600, color: colors.text }}>Identity & Classification</span>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
          <div>
            <label style={{ display: 'block', fontSize: '12px', fontWeight: 600, color: colors.textSecondary, marginBottom: '6px' }}>Guardrail Name</label>
            <input value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Maximum Discount Limit" style={inputStyle} />
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '12px', fontWeight: 600, color: colors.textSecondary, marginBottom: '6px' }}>Description</label>
            <textarea value={description} onChange={e => setDescription(e.target.value)}
              placeholder="A human-readable explanation of what this guardrail enforces and why it exists."
              rows={2} style={{ ...inputStyle, resize: 'vertical', lineHeight: 1.6 }}
            />
          </div>

          <div style={{ display: 'flex', gap: '24px', flexWrap: 'wrap' }}>
            {/* Scope / Level */}
            <div>
              <label style={{ display: 'block', fontSize: '12px', fontWeight: 600, color: colors.textSecondary, marginBottom: '8px' }}>Scope</label>
              <div style={{ display: 'flex', gap: '8px' }}>
                {[
                  { id: 'organization', label: 'Organization', icon: Globe, desc: 'Always enforced' },
                  { id: 'goal', label: 'Goal-Specific', icon: Target, desc: 'Linked to goals' },
                ].map(opt => {
                  const Icon = opt.icon;
                  const isActive = level === opt.id;
                  return (
                    <button key={opt.id} onClick={() => setLevel(opt.id)} style={{
                      padding: '8px 16px', borderRadius: theme.radii.md,
                      border: `1px solid ${isActive ? theme.colors.blue + '50' : colors.border}`,
                      backgroundColor: isActive ? `${theme.colors.blue}08` : 'transparent',
                      color: isActive ? theme.colors.blue : colors.textSecondary,
                      fontSize: '12px', fontWeight: 600, cursor: 'pointer', fontFamily: theme.fonts.body,
                      display: 'flex', alignItems: 'center', gap: '6px',
                    }}>
                      <Icon size={13} /> {opt.label}
                    </button>
                  );
                })}
              </div>
              <p style={{ fontSize: '11px', color: colors.textTertiary, margin: '6px 0 0', maxWidth: '360px', lineHeight: 1.4 }}>
                {level === 'organization'
                  ? 'This guardrail will be enforced across all goals and sub-agents — no goal linking needed.'
                  : 'This guardrail will only activate when one of the linked goals is running.'}
              </p>
            </div>

            {/* Severity */}
            <div>
              <label style={{ display: 'block', fontSize: '12px', fontWeight: 600, color: colors.textSecondary, marginBottom: '8px' }}>Severity</label>
              <div style={{ display: 'flex', gap: '8px' }}>
                {['critical', 'warning'].map(s => {
                  const sc = s === 'critical' ? theme.colors.error : theme.colors.warning;
                  const sb = s === 'critical' ? theme.colors.errorMuted : theme.colors.warningMuted;
                  return (
                    <button key={s} onClick={() => setSeverity(s)} style={{
                      padding: '7px 18px', borderRadius: theme.radii.full,
                      border: `1px solid ${severity === s ? sc + '40' : colors.border}`,
                      backgroundColor: severity === s ? sb : 'transparent',
                      color: severity === s ? sc : colors.textSecondary,
                      fontSize: '12px', fontWeight: 600, cursor: 'pointer', fontFamily: theme.fonts.body,
                      textTransform: 'capitalize', display: 'flex', alignItems: 'center', gap: '5px',
                    }}>
                      <AlertTriangle size={12} /> {s}
                    </button>
                  );
                })}
              </div>
              <p style={{
                fontSize: '11px', color: colors.textTertiary, margin: '6px 0 0',
                lineHeight: '1.4', maxWidth: '420px',
              }}>
                {severity === 'critical'
                  ? 'Hard block — the action is stopped. In Autopilot, escalates to human.'
                  : 'Soft flag — agent is warned but can override. Logged for audit.'}
              </p>
            </div>

            {/* Status */}
            <div>
              <label style={{ display: 'block', fontSize: '12px', fontWeight: 600, color: colors.textSecondary, marginBottom: '8px' }}>Status</label>
              <div style={{ display: 'flex', gap: '8px' }}>
                {['active', 'inactive'].map(s => (
                  <button key={s} onClick={() => setStatus(s)} style={{
                    padding: '7px 18px', borderRadius: theme.radii.full,
                    border: `1px solid ${status === s ? (s === 'active' ? theme.colors.success : colors.textTertiary) + '40' : colors.border}`,
                    backgroundColor: status === s ? (s === 'active' ? theme.colors.successMuted : colors.surfaceHover) : 'transparent',
                    color: status === s ? (s === 'active' ? theme.colors.success : colors.textSecondary) : colors.textSecondary,
                    fontSize: '12px', fontWeight: 600, cursor: 'pointer', fontFamily: theme.fonts.body, textTransform: 'capitalize',
                  }}>
                    {s}
                  </button>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ── 2. Trigger Condition ── */}
      <div style={sectionStyle}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}>
          <AlertTriangle size={15} color={theme.colors.error} />
          <span style={{ fontSize: '14px', fontWeight: 600, color: colors.text }}>Trigger Condition</span>
        </div>
        <p style={{ fontSize: '12px', color: colors.textSecondary, margin: '0 0 14px' }}>
          WHEN does this guardrail fire? The AI engine evaluates this at runtime.
        </p>
        <textarea value={condition} onChange={e => setCondition(e.target.value)}
          placeholder='e.g. "When Apply_Billing_Credit action is triggered with amount > $500"'
          rows={3} style={{ ...inputStyle, fontFamily: "'Space Grotesk', monospace", lineHeight: 1.7, resize: 'vertical' }}
        />
      </div>

      {/* ── 3. Constraint / Enforcement ── */}
      <div style={sectionStyle}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}>
          <Shield size={15} color={sevColor} />
          <span style={{ fontSize: '14px', fontWeight: 600, color: colors.text }}>Constraint / Enforcement</span>
        </div>
        <p style={{ fontSize: '12px', color: colors.textSecondary, margin: '0 0 14px' }}>
          WHAT happens when the trigger fires — block, restrict, notify, mask, etc.
        </p>
        <textarea value={constraint} onChange={e => setConstraint(e.target.value)}
          placeholder='e.g. "Block auto-execution. Surface supervisor approval prompt."'
          rows={3} style={{ ...inputStyle, fontFamily: "'Space Grotesk', monospace", lineHeight: 1.7, resize: 'vertical' }}
        />
      </div>

      {/* ── 4. Applicable Goals (only for goal-level) ── */}
      {level === 'goal' && (
        <div style={sectionStyle}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '6px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Target size={15} color={theme.colors.blue} />
              <span style={{ fontSize: '14px', fontWeight: 600, color: colors.text }}>Applied To Goals</span>
            </div>
            <div style={{ position: 'relative' }} ref={pickerRef}>
              <button onClick={() => { setShowGoalPicker(!showGoalPicker); setGoalSearch(''); }} style={{
                padding: '5px 14px', borderRadius: theme.radii.md, border: `1px solid ${theme.colors.blue}30`,
                backgroundColor: `${theme.colors.blue}06`, color: theme.colors.blue,
                fontSize: '12px', fontWeight: 600, cursor: 'pointer', fontFamily: theme.fonts.body,
                display: 'flex', alignItems: 'center', gap: '4px',
              }}>
                <Plus size={12} /> Add Goal
              </button>

              {showGoalPicker && (
                <div style={{
                  position: 'absolute', top: '100%', right: 0, marginTop: '4px', width: '340px',
                  backgroundColor: colors.surface, border: `1px solid ${colors.border}`,
                  borderRadius: theme.radii.lg, boxShadow: theme.shadows.dropdown,
                  zIndex: 120, maxHeight: '300px', display: 'flex', flexDirection: 'column',
                }}>
                  <div style={{
                    padding: '8px 12px', borderBottom: `1px solid ${colors.border}`,
                    display: 'flex', alignItems: 'center', gap: '8px',
                  }}>
                    <Search size={13} color={colors.textSecondary} />
                    <input placeholder="Search goals..." value={goalSearch} onChange={e => setGoalSearch(e.target.value)} autoFocus
                      style={{ flex: 1, border: 'none', outline: 'none', backgroundColor: 'transparent', color: colors.text, fontSize: '12px', fontFamily: theme.fonts.body }}
                    />
                  </div>
                  <div style={{ overflowY: 'auto', flex: 1 }}>
                    {filteredGoals.map(g => {
                      const goalStatusColor = g.status === 'active' ? theme.colors.success : theme.colors.warning;
                      return (
                        <button key={g.id} onClick={() => { setSelectedGoals(prev => [...prev, g.id]); setShowGoalPicker(false); setGoalSearch(''); }}
                          style={{
                            width: '100%', display: 'flex', alignItems: 'center', gap: '10px',
                            padding: '9px 12px', border: 'none', backgroundColor: 'transparent',
                            cursor: 'pointer', textAlign: 'left', fontFamily: theme.fonts.body,
                            transition: theme.transitions.fast,
                          }}
                          onMouseEnter={e => e.currentTarget.style.backgroundColor = colors.surfaceHover}
                          onMouseLeave={e => e.currentTarget.style.backgroundColor = 'transparent'}
                        >
                          <div style={{ width: '8px', height: '8px', borderRadius: '50%', backgroundColor: goalStatusColor, flexShrink: 0 }} />
                          <div style={{ flex: 1 }}>
                            <div style={{ fontSize: '12px', fontWeight: 600, color: colors.text }}>{g.name}</div>
                            <div style={{ fontSize: '10px', color: colors.textSecondary }}>{g.status}</div>
                          </div>
                          <Plus size={12} color={theme.colors.blue} />
                        </button>
                      );
                    })}
                    {filteredGoals.length === 0 && (
                      <div style={{ padding: '16px', textAlign: 'center' }}>
                        <p style={{ fontSize: '12px', color: colors.textSecondary, margin: 0 }}>
                          {availableGoals.length === 0 ? 'All goals already added.' : 'No matches.'}
                        </p>
                      </div>
                    )}
                  </div>
                </div>
              )}
            </div>
          </div>
          <p style={{ fontSize: '12px', color: colors.textSecondary, margin: '0 0 14px' }}>
            Select which Goals this guardrail applies to.
          </p>

          {selectedGoals.length > 0 ? (
            <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
              {selectedGoals.map(gid => {
                const g = allGoals.find(gl => gl.id === gid);
                if (!g) return null;
                return (
                  <span key={gid} style={{
                    padding: '5px 10px', borderRadius: theme.radii.full,
                    backgroundColor: `${theme.colors.blue}08`, border: `1px solid ${theme.colors.blue}20`,
                    fontSize: '12px', fontWeight: 500, color: theme.colors.blue,
                    display: 'flex', alignItems: 'center', gap: '6px',
                  }}>
                    <Target size={11} /> {g.name}
                    <button onClick={() => setSelectedGoals(prev => prev.filter(id => id !== gid))}
                      style={{ padding: 0, border: 'none', backgroundColor: 'transparent', cursor: 'pointer', display: 'flex' }}>
                      <X size={11} color={theme.colors.blue} />
                    </button>
                  </span>
                );
              })}
            </div>
          ) : (
            <div style={{ padding: '14px', borderRadius: theme.radii.md, border: `1px dashed ${colors.border}`, textAlign: 'center' }}>
              <span style={{ fontSize: '12px', color: colors.textTertiary }}>No goals selected — add at least one goal for this guardrail to activate</span>
            </div>
          )}
        </div>
      )}

      {/* ── Live Preview ── */}
      {(name || condition || constraint) && (
        <div style={{
          padding: '20px', borderRadius: theme.radii.xl,
          backgroundColor: `${sevColor}02`, border: `1px solid ${sevColor}15`,
          marginBottom: '20px',
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '12px' }}>
            <AlertTriangle size={14} color={sevColor} />
            <span style={{ fontSize: '12px', fontWeight: 700, color: colors.textSecondary, textTransform: 'uppercase', letterSpacing: '0.4px' }}>Preview</span>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '8px' }}>
            <span style={{ fontSize: '14px', fontWeight: 600, color: colors.text }}>{name || 'Untitled Guardrail'}</span>
            <span style={{
              padding: '2px 7px', borderRadius: theme.radii.full, fontSize: '10px', fontWeight: 700,
              backgroundColor: sevBg, color: sevColor, textTransform: 'uppercase',
            }}>{severity}</span>
            <span style={{
              padding: '2px 7px', borderRadius: theme.radii.full, fontSize: '10px', fontWeight: 600,
              backgroundColor: level === 'organization' ? `${theme.colors.blue}08` : `${theme.colors.purple}08`,
              color: level === 'organization' ? theme.colors.blue : theme.colors.purple,
            }}>{level === 'organization' ? 'Organization' : 'Goal-Specific'}</span>
          </div>
          <p style={{ fontSize: '12px', color: colors.textSecondary, margin: '0 0 12px' }}>{description || 'No description'}</p>
          {condition && (
            <div style={{ marginBottom: '8px' }}>
              <div style={{ fontSize: '10px', fontWeight: 700, color: colors.textTertiary, textTransform: 'uppercase', marginBottom: '4px' }}>Trigger</div>
              <div style={{
                padding: '8px 12px', borderRadius: theme.radii.md, backgroundColor: colors.surfaceHover,
                fontSize: '12px', color: colors.text, lineHeight: 1.5, fontFamily: "'Space Grotesk', monospace",
              }}>{condition}</div>
            </div>
          )}
          {constraint && (
            <div>
              <div style={{ fontSize: '10px', fontWeight: 700, color: colors.textTertiary, textTransform: 'uppercase', marginBottom: '4px' }}>Enforcement</div>
              <div style={{
                padding: '8px 12px', borderRadius: theme.radii.md, backgroundColor: colors.surfaceHover,
                fontSize: '12px', color: colors.text, lineHeight: 1.5, fontFamily: "'Space Grotesk', monospace",
              }}>{constraint}</div>
            </div>
          )}
        </div>
      )}

      {/* ── Validation ── */}
      {!isValid && (name || description || condition || constraint) && (
        <div style={{
          padding: '14px 20px', borderRadius: theme.radii.lg,
          backgroundColor: `${theme.colors.warning}06`, border: `1px solid ${theme.colors.warning}20`,
          marginBottom: '20px', display: 'flex', alignItems: 'flex-start', gap: '10px',
        }}>
          <AlertTriangle size={15} color={theme.colors.warning} style={{ flexShrink: 0, marginTop: '1px' }} />
          <div style={{ fontSize: '12px', color: colors.textSecondary, lineHeight: 1.6 }}>
            <strong style={{ color: colors.text }}>Required fields missing:</strong>
            {!name.trim() && <span style={{ display: 'block' }}>• Guardrail name</span>}
            {!description.trim() && <span style={{ display: 'block' }}>• Description</span>}
            {!condition.trim() && <span style={{ display: 'block' }}>• Trigger condition</span>}
            {!constraint.trim() && <span style={{ display: 'block' }}>• Constraint / enforcement</span>}
          </div>
        </div>
      )}

      {/* ── Bottom Actions ── */}
      <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '10px', marginBottom: '40px' }}>
        <button onClick={onBack} style={{
          padding: '9px 22px', borderRadius: theme.radii.md, border: `1px solid ${colors.border}`,
          backgroundColor: 'transparent', color: colors.textSecondary,
          fontSize: '13px', fontWeight: 600, cursor: 'pointer', fontFamily: theme.fonts.body,
        }}>
          Cancel
        </button>
        <button onClick={handleSave} disabled={!isValid} style={{
          padding: '9px 22px', borderRadius: theme.radii.md, border: 'none',
          backgroundColor: isValid ? theme.colors.blue : colors.surfaceHover,
          color: isValid ? '#fff' : colors.textTertiary,
          fontSize: '13px', fontWeight: 600, cursor: isValid ? 'pointer' : 'not-allowed',
          fontFamily: theme.fonts.body, display: 'flex', alignItems: 'center', gap: '6px',
          transition: theme.transitions.fast, opacity: isValid ? 1 : 0.7,
        }}>
          <Save size={14} /> {isEdit ? 'Save Changes' : 'Create Guardrail'}
        </button>
      </div>
    </div>
  );
}
